### PR TITLE
recur on the right variable, fixes #30

### LINKED ISSUE #30: two wrongs make a right?
In the [example](https://github.com/ekmett/bound/blob/master/examples/Imperative.hs) I recently contributed, I made two mistakes which happen to cancel each other out: `pInstantiate1` and `pAbstract1` both recur over the wrong variable, and as a result bound variables behave like De Bruijn indices instead of De Bruijn levels.

Despite this, the example works fine, because it only manipulates variables via those two functions and they both use the same numbering convention. Since the fix is a bit hairy, maybe it would be better to keep the example as is?

Details after the cut.

---

## the problem

The easiest way to see why this is a mistake is to generalize the signature of `pInstantiate` so that it accepts a `Scope b operand` instead of just `Scope () operand`, just like the original `instantiate1` does. The given `Prog (Scope b operand) a` contains a bunch of `Scope b operand a` sub-terms, which in turn contain variables of type `Var b a`, and `pInstantiate` is supposed to instantiate all the variables of type `b` with the term `x` ("instantiate `b` with `x`" for short).

    pInstantiate1 :: Monad operand
                  => operand a
                  -> Prog (Scope b operand) a
                  -> Prog operand a
    pInstantiate1 x (Add ... cc) = Add ... (pInstantiate1 (lift x) cc)

Since `cc` has type `Prog (Scope () (Scope b operand)) a`, the recursive call instantiates `()` with `x` instead of instantiating `b` with `x`. Oops!

## the complicated solution

To recur on `b` instead, I'd need a more general type accepting a `Scope b` regardless of the number of nested `Scope ()` wrappers under which it is hidden:

    pInstantiate1 :: Monad operand
                  => operand a
                  -> Prog (Scope () (Scope () ... (Scope b operand))) a
                  -> Prog (Scope () (Scope () ... operand)) a
    pInstantiate1 x (Add ... cc) = Add ... (pInstantiate1 x cc)

I can implement this and `pAbstract1` using about 50 lines of type-level machinery, but doing so makes the example a lot less appealing.

## the slow solution

To keep the types simple, I can temporarily hide the `Scope ()` within the `a`, leaving only the `Scope b` on which we can safely recur, after which I'd recreate the `Scope ()`.

    pInstantiate1 :: forall operand a. (Monad operand, Eq a)
                  => operand a
                  -> Prog (Scope () operand) a
                  -> Prog operand a
    pInstantiate1 x (Ret o)        = Ret (instantiate1 x o)
    pInstantiate1 x (Add o1 o2 cc) = Add (instantiate1 x o1)
                                         (instantiate1 x o2)
                                         cc'
      where
        cc' :: Prog (Scope () operand) a
        cc' = fmap fromJust
            $ pAbstract1 Nothing
            $ pInstantiate1 (fmap Just x)
            $ pInstantiate1 (pure Nothing)
            $ fmap Just cc

This works, but since `pAbstract1` is implemented the same way, the complexity for *n* nested binders is *O(3^n)*, quite steep!

---

So, what should we do? Keep the morally-wrong-but-working solution, implement the correct-but-complicated solution, or implement the correct-but-slow solution? Or maybe there's a better solution I'm not seeing?

### PR DESCRIPTION
**Pull request by gelisam**

### CODE REVIEW

File: examples/Imperative.hs [hunk 1]
```diff
@@ -73,23 +76,37 @@ data Prog operand a
...
+pInstantiate1 = go instantiate1
+  where
+    go :: forall o o' u
+        . (forall v. operand v -> o v -> o' v)
+       -> operand u -> Prog o u -> Prog o' u
+    go f x (Ret o)        = Ret (f x o)
+    go f x (Add o1 o2 cc) = Add (f x o1) (f x o2)
+                          $ go f' x cc
+      where
+        f' :: operand v -> Scope () o v -> Scope () o' v
```
Comment (phadej) [inline examples/Imperative.hs]: Could you comment how `f'` is different from `f`, and why we need one? Now this looks complex for no reason (maybe more obvious when you see the diff, but not so otherwise).

**Comment by phadej** [comment]
Did I understand right, that as you had *two wrongs makes one right* situation, there isn't an example which didn't work without this change? If there isn't such (otherwise it would be nice to add it), then I'll be happy to merge this.

Or can the "indices vs levels" be somehow highlighted, why we want to do this (a bit more complicated) way? If we print out the structure? (you can make it work for ghc-7.8 / transformers-0.4, I can than the more complicated `transformers-0.5` `Show1`instance, if it's problematic.

 Sorry for asking stupid questions, but maybe someone else might found this difficult as well. Also printing out the structure might make the example even more clear.

Thanks for your work anyway!

**Comment by gelisam** [comment]
> Did I understand right, [...] can the "indices vs levels" be somehow highlighted [...] printing out the structure might make the example even more clear.

I'll try to make everything crystal clear to you first, then we can decide together what would be the best way to present it to users.

First, let's define a more convenient term language. In `Prog` the only way to examine variables is via `Add`, and it only allows two variables to be examined before it introduces a new binder. Let's instead define a language which allows us to examine as many variables as we want.

    data Exp operand a
      = Trace [operand a]
              (Exp (Scope () operand) a)
      | Done
      deriving (Functor,Foldable,Traversable)

Then, let's define `eBadInstantiate1` and `eBadAbstract1` using the two-wrongs approach, and `eInstantiate1` and `eAbstract1` using the more complicated approach.

**Comment by gelisam** [comment]
> you can make it work for ghc-7.8 / transformers-0.4, I can than the more complicated `transformers-0.5` `Show1` instance, if it's problematic.)

Since implementing a `Show` instance across GHC versions is complicated, we can simply bypass it by using the built-in pretty-printer which ghci's `:force` is using, assuming the format hasn't changed between versions. It's also usable in doctests.


> Did I understand right, [...] can the "indices vs levels" be somehow highlighted [...] printing out the structure might make the example even more clear.

I'll try to make everything crystal clear to you first, then we can decide together how much of it we want to present to users and in which form.

First, let's define a more convenient term language. In `Prog` the only way to examine variables is via `Add`, and it only allows two variables to be examined before it introduces a new binder. Let's instead define a different two-level language which allows us to examine as many variables as we want.

    data Exp a
      = Var a
      | ETrace [Exp a] (Exp a)
      | EBind (Scope () Exp a)
      | EDone
      deriving (Functor,Foldable,Traversable)


    data Term exp a
      = Trace [exp a] (Term exp a)
      | Bind (Term (Scope () exp) a)
      | Done
      deriving (Functor,Foldable,Traversable)

    instance Applicative Exp where ...
    instance Monad Exp where ...

    -- the "two wrongs" version
    tBadInstantiate1 :: Monad exp => exp a -> Term (Scope () exp) a -> Term exp a
    tBadAbstract1 :: (Monad exp, Eq a) => a -> Term exp a -> Term (Scope () exp) a

    tInstantiate1 :: Monad exp => exp a -> Term (Scope b exp) a -> Term exp a
    tAbstract1 :: (Monad exp, Eq a) => a -> Term exp a -> Term (Scope () exp) a


Let's look at the way bound is representing its variables in a normal, non-sideways setting.

    e :: Scope () Exp String
    e = abstract1 "x" $ ETrace [Var "x"] $ EBind
      $ abstract1 "y" $ ETrace [Var "x", Var "y"] $ EBind
      $ abstract1 "z" $ ETrace [Var "x", Var "y", Var "z"] $ EDone
    
    >>> :force e
    e = Scope (ETrace
                 [Var (B ())]
                 (EBind
                    (Scope (ETrace
                              [Var (F (B ())),Var (B ())]
                              (EBind
                                 (Scope (ETrace
                                           [Var (F (F (B ()))),Var (F (B ())),Var (B ())] EDone)))))))



Let me rearrange that into something more readable:

    >>> :force e
    e = Scope $ ETrace [ Var $ B ()         -- x
                       ] $ EBind
      $ Scope $ ETrace [ Var $ F $ B ()     -- x
                       , Var $ B ()         -- y
                       ] $ EBind
      $ Scope $ ETrace [ Var $ F $ F $ B () -- x
                       , Var $ F $ B ()     -- y
                       , Var $ B ()         -- z
                       ] $ EDone

We can see that De Bruijn indices are used: `B ()` means the variable bound by the closest binder, and `F $ B ()` means the variable bound by the second-closest binder.

Next, let's see what `tBadAbstract1` does instead.

    badTerm :: Term (Scope () Exp) String
    badTerm = tBadAbstract1 "x" $ Trace [Var "x"] $ Bind
            $ tBadAbstract1 "y" $ Trace [Var "x", Var "y"] $ Bind
            $ tBadAbstract1 "z" $ Trace [Var "x", Var "y", Var "z"] $ Done
    
    >>> :force badTerm
    badTerm = Trace [ Scope $ Var $ B ()                         -- x
                    ] $ Bind
            $ Trace [ Scope $ Scope $ Var $ F $ B ()             -- x
                    , Scope $ Scope $ Var $ B ()                 -- y
                    ] $ Bind
            $ Trace [ Scope $ Scope $ Scope $ Var $ F $ F $ B () -- x
                    , Scope $ Scope $ Scope $ Var $ F $ B ()     -- y
                    , Scope $ Scope $ Scope $ Var $ B ()         -- z
                    ] $ Done

It also uses De Bruijn indices. So what's the problem? Well, it's a bit hard to see the problem because all the `()` values look the same. So to make things clearer, let's define three distinct unit types and three corresponding binders:

    data X = X deriving (Show, Eq)
    data Y = Y deriving (Show, Eq)
    data Z = Z deriving (Show, Eq)

    data Exp' a
      = Var' a
      | ETrace' [Exp' a] (Exp' a)
      | EBindX' (Scope X Exp' a)
      | EBindY' (Scope Y Exp' a)
      | EBindZ' (Scope Z Exp' a)
      | EDone'
      deriving (Functor,Foldable,Traversable)

    data Term' exp a
      = Trace' [exp a] (Term' exp a)
      | BindX' (Term (Scope X exp) a)
      | BindY' (Term (Scope Y exp) a)
      | BindZ' (Term (Scope Z exp) a)
      | Done'
      deriving (Functor,Foldable,Traversable)

With those more specific binders, each `()` is replaced by a unit value indicating which binder introduced it:

    e' :: Scope X Exp' a
    e' = Scope $ ETrace' [ Var' $ B X         -- x
                         ] $ EBindY'
       $ Scope $ ETrace' [ Var' $ F $ B X     -- x
                         , Var' $ B Y         -- y
                         ] $ EBindZ'
       $ Scope $ ETrace' [ Var' $ F $ F $ B X -- x
                         , Var' $ F $ B Y     -- y
                         , Var' $ B Z         -- z
                         ] $ EDone'

    badTerm' :: Term' (Scope X Exp') a
    badTerm' = Trace' [ Scope $ Var' $ B X                         -- x
                      ] $ BindY'
             $ Trace' [ Scope $ Scope $ Var' $ F $ B Y             -- x
                      , Scope $ Scope $ Var' $ B X                 -- y
                      ] $ BindZ'
             $ Trace' [ Scope $ Scope $ Scope $ Var' $ F $ F $ B Z -- x
                      , Scope $ Scope $ Scope $ Var' $ F $ B Y     -- y
                      , Scope $ Scope $ Scope $ Var' $ B X         -- z
                      ] $ Done'

We can now see the problem quite clearly! The innermost binder, a `BindZ'`, introduces the new value `F $ F $ B Z`, but `tBadAbstract1` uses it to represent "x" instead of using it to represent the newly-bound variable "z".

So why is the double-`F` variable `F $ F $ B X` when using `Exp`, but `F $ F $ B Z` when using `Term`? The difference is that `Exp` introduces variables by modifying its `a` type parameter, while `Term` introduces variables by modifying its `exp` type parameter. So when `EBindZ'` receives an `a` which already holds representations for "x" and "y", it constructs the larger type `Var Z a` which also holds a representation for "z", namely `B Z`. And when `BindZ'` receives an `exp` which already adds representations of "x" and "y" to a type parameter `a'`, it constructs the larger type constructor `Scope Z exp`. This construction in turn receives a type parameter `a`, which it extends to `Var Z a`, and then passes this `a'` to `exp`, which further extends it to `Var X (Var Y (Var Z a))`. Hence `F $ F $ B Z`.

Okay, so we have now established that `BindZ'` should use `F $ F $ B Z` to refer to the newly-bound variable "z" and `B X` to refer to the outermost binder:

    term' :: Term' (Scope X Exp') a
    term' = Trace' [ Scope $ Var' $ B X                         -- x
                   ] $ BindY'
          $ Trace' [ Scope $ Scope $ Var' $ B X                 -- x
                   , Scope $ Scope $ Var' $ F $ B Y             -- y
                   ] $ BindZ'
          $ Trace' [ Scope $ Scope $ Scope $ Var' $ B X         -- x
                   , Scope $ Scope $ Scope $ Var' $ F $ B Y     -- y
                   , Scope $ Scope $ Scope $ Var' $ F $ F $ B Z -- z
                   ] $ Done'

That is, we should use De Bruijn levels instead of De Bruijn indices: `B ()` refers to the outermost binder, `F $ B ()` refers to the second outermost binder, and so on. And this is exactly what the corrected, more complicated `tAbstract1` does:

    term :: Term (Scope () Exp) String
    term = tAbstract1 "x" $ Trace [Var "x"] $ Bind
         $ tAbstract1 "y" $ Trace [Var "x", Var "y"] $ Bind
         $ tAbstract1 "z" $ Trace [Var "x", Var "y", Var "z"] $ Done
    
    >>> :force term
    term = Trace [ Scope $ Var $ B ()
                 ] $ Bind
         $ Trace [ Scope $ Scope $ Var $ B ()
                 , Scope $ Scope $ Var $ F $ B ()
                 ] $ Bind
         $ Trace [ Scope $ Scope $ Scope $ Var $ B ()
                 , Scope $ Scope $ Scope $ Var $ F $ B ()
                 , Scope $ Scope $ Scope $ Var $ F $ F $ B ()
                 ] $ Done

> there isn't an example which didn't work without this change?

The simple approach does not type check when applied to a language which doesn't always bind `()`, so that's one case in which it doesn't work. If we do have a language in which every binder uses `()`, then the simple and complicated approaches both use the same `Var () (Var () (Var ... a))` types to represent the variables: basically, a De Bruijn number or a free variable. The only difference is whether that number is interpreted as counting from the outside or from the inside. I haven't tested many expressions, but as long as the numbering scheme is used consistently, I don't see how this could lead to problems.

Since it works, I'd be fine with leaving the simple code as is, in order to simplify the exposition. The main reason I want to publish a fix is because finding this fix was quite tricky. So if I don't publish it, a user might try to implement a language with non-`()` binders based on the simple example code, it won't work, and they might be stuck for a long time.

Instead of making the example more complicated, perhaps it would be better to add a separate example? Maybe a part 3 at the end of `Imperative.hs`, or maybe a separate file dedicated to explaining the difference between De Bruijn indices and De Bruijn levels?
